### ISSUE TITLE
When we login after logout in  ionic app, some time this error comes.

### ISSUE THREAD

**Issue by jeetkapadia** [cometchat-pro/cordova-ionic-chat-sdk#1]
When we login after logout in  ionic app, some time this error comes.
API - https://apiclient-us.cometchat.io/v2.0/me
RESPONSE - {"error":{"code":"AUTH_ERR_AUTH_TOKEN_NOT_FOUND","message":"The auth token <your auth token > does not exist. Please make sure you are logged in and have a valid auth token or try login again."}}
While a new token created everytime i login. As you can see in screen shot it exist (edited)

**Comment by mayur-bhandari** [comment]
Hello @jeetkapadia, this issue has been resolved in our latest release v2.0.5
