### ISSUE TITLE
ionic-calls Plugin requires Access to Calendar on iOS. App Store rejects App because of "Missing Purpose String in Info.plist"

### ISSUE THREAD

**Issue by kamekaioken** [cometchat-pro/cordova-ionic-chat-sdk#10]
### Describe the problem

The ionic calls Plugin seems to ask for Calendar access. My App was rejected by the App Store with this explanation:
"TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data."

The integration of the plugin is the only change I made. All my other builds were accepted by the App Store.

### What was the expected behavior?

My App should not face any acceptance issues by the App Store. Please update the plugin to avoid accessing Calendar or make it clear in the documentation that integrators like me need to provide an entry in the Info.plist.
Please provide a fix or an explanation why the calendar data is needed very soon. 

### Reproduction

- Build Capacitor App for iOS with @cometchat-pro/ionic-calls
- Deploy to App Store Connect
- Build is made invalid by Apple

### Environment

- "@angular/core": "~10.0.0"
- "@ionic/angular": "^5.5.2"
- "@cometchat-pro/cordova-ionic-chat": "2.3.4"
- "@cometchat-pro/ionic-calls": "2.0.2"

**Comment by proveshapyne** [comment]
Hello @kamekaioken!

We have reached out to your email regarding the issue reported. I would appreciate it if we could continue our conversation via email. Therefore, I am closing out this ticket.

Thank you!

Regards,
Provesha

**Comment by mayur-bhandari** [comment]
Hello @kamekaioken,

We have fixed this issue in the latest release. Please update the CometChat Cordova Ionic SDK(@cometchat-pro/cordova-ionic-chat) to `v2.4.1` & CometChat Ionic Calls(@cometchat-pro/ionic-calls) to `v2.1.2`. Please let us know if you are still facing this issue.

**Comment by kamekaioken** [comment]
Thanks, the update solved the issue.
