### ISSUE TITLE
Tap on Push Notification doesn't open up the app

### ISSUE THREAD

**Issue by agrajj** [cometchat-pro/cordova-ionic-chat-sdk#6]
### Describe the problem

> I am using this SDK and able to configure it to receive Push Notification for new messages. However when I tap on the notification same doesn't open up my Ionic App. I want to redirect user to the chat conversations screen upon tapping the notification for new messages.

> This has to do something with how Comet Chat Server is sending out push notifications because when I use FCM api to send notifications my app does open up without any issue.

### What was the expected behavior?

> App should come to foreground if already running or start afresh when tapping on push notification.

### Ionic Info
Ionic:

   Ionic CLI          : 6.12.1 (/Users/agraj/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.3, (and 27 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.1.0

System:

   Android SDK Tools : 26.1.1 (/Users/agraj/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : ios-sim/9.0.0 darwin-x64 node-v12.18.3
   NodeJS            : v12.18.3 (/Users/agraj/.nvm/versions/node/v12.18.3/bin/node)
   npm               : 6.14.8
   OS                : macOS Big Sur
   Xcode             : Xcode 12.4 Build version 12D4e

### package.json
...
"@cometchat-pro/cordova-ionic-chat": "^2.2.0"
...

**Comment by mayur-bhandari** [comment]
Hello @agrajj,

Currently, CometChat sends a "click_action": "FCM_PLUGIN_ACTIVITY" so you would have to add the following lines in your AndroidManifest.xml,

`<intent-filter><action android:name="FCM_PLUGIN_ACTIVITY" /><category android:name="android.intent.category.DEFAULT" /></intent-filter>`

I have created a feature request to customize the payload and I have added you to the feature request. You can follow the feature request [here](https://feedback.cometchat.com/cometchat-pro-feature-requests/p/push-notification-notification-key).

Warm Regards,

CometChat Pro
Mayur Bhandari

**Comment by proveshapyne** [comment]
Hello @agrajj,

Hope this was helpful.
Please feel free to reach out to us at help@cometchat.com if you need technical aid.

Regards,
Provesha
