### ISSUE TITLE
Ionic Capacitor Call Plugin produces 'CocoaPods could not find compatible versions for pod "CometChatCalls"' on iOS target build

### ISSUE THREAD

**Issue by kamekaioken** [cometchat-pro/cordova-ionic-chat-sdk#7]
### Describe the problem
Since a github repository doesn't exist (anymore) for this package [@cometchat-pro/ionic-calls](https://www.npmjs.com/package/@cometchat-pro/ionic-calls), I'm reporting the bug here. I hope this is ok.

While trying to integrate audio and video call into my ionic app the command `ionic cap sync ios` produces an error.
The error message:

```
[!] CocoaPods could not find compatible versions for pod "CometChatCalls":
        In Podfile:
        CometchatProIonicCalls (from `../../node_modules/@cometchat-pro/ionic-calls`) was
        resolved to 0.0.9, which depends on
        CometChatCalls (= 1.0.1-beta2)

        None of your spec sources contain a spec satisfying the dependency: `CometChatCalls
        (= 1.0.1-beta2)`.`
```

### What was the expected behavior?
Capacitor should sync with the iOS project.

### Reproduction
in ionic project run:
`npm i @cometchat-pro/ionic-calls`
`ionic cap sync ios`

### Environment
Angular 10, Ionic 5 and Capacitor 3

"@cometchat-pro/chat": "2.2.0",
"@cometchat-pro/cordova-ionic-chat": "2.2.0",
"@cometchat-pro/ionic-calls": "0.0.9",
"@capacitor/core": "^3.0.0-beta.6",
"@ionic-native/core": "^5.30.0",
"@ionic/angular": "^5.5.2",

**Comment by mayur-bhandari** [comment]
Hello @kamekaioken,

Can you please try using `@comet-pro/ionic-calls v0.0.8` and check if everything is working fine. I will get this checked and update you once I have some details on the same. 

CometChat Pro,
Mayur Bhandari

**Comment by kamekaioken** [comment]
@mayur-bhandari thank you for the quick response.

`ionic cap sync ios` is working for v0.0.8

But when trying to build and run the iOS App in Xcode I receive the error: `Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0` coming from the CometChat Pods. I manually changed their target build to iOS 12.0 since my target build is iOS 12.

But still I couldn't manage to actually perform audio and video call. Is there any sample code which shows how to integrate audio and video calling in an ionic app? I mean not only a setup like [explained here](https://prodocs.cometchat.com/docs/cordova-ionic-setup) but further more a code sample like the [Comet Chat Angular UI kit](https://prodocs.cometchat.com/docs/js-angular-ui-kit) which includes audio and video calling. I tried using this code base, but unfortunately it doesn't seem to work with capacitor. After accepting a call in an iOS app the following error is thrown (the javascript error seems to be thrown because of the Swift/Ojective-C errors relative to a webkit bug using audio or video tags in HTML):

```
[assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}>
2021-03-12 11:31:05.643230+0100 App[4878:91546] [ProcessSuspension] 0x114d68240 - ProcessAssertion: Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' for process with PID 4899, error: Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}
2021-03-12 11:31:05.644015+0100 App[4878:91546] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}>
2021-03-12 11:31:05.644100+0100 App[4878:91546] [ProcessSuspension] 0x114d68270 - ProcessAssertion: Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' for process with PID 4878, error: Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}
⚡️  [error] - ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'X.startCall')
```

For now I can live with version 0.0.8 and manually changing the target build to 12 (if you can confirm that this should work without any problem). But my question now is: how to perform a working call inside an ionic app in the example of iOS? Sorry if this doesn't belong to this issue tracker.

**Comment by mayur-bhandari** [comment]
Hello @kamekaioken ,

You can check the ionic sample app [here](https://github.com/cometchat-pro/cordova-ionic-chat-app/tree/calling). Hope this helps.

CometChat Pro,
Mayur Bhandari

**Comment by kamekaioken** [comment]
@mayur-bhandari Thank you, I had only eyes for the master branch which is missing the calling feature 😄

**Comment by kamekaioken** [comment]
Unfortunately `CometChat.startCall(callSettings);` is behaving odd in my App. I can see in the logs that the call is started and both parties can join the call, but no call screen is shown to me.
In your Sample App it seems to work, after accepting a call in the calling-screen and both clients calling `startCall()` the expected call screen is displayed. Copying almost everything from your sample App into my App which is running on Capacitor 3, Ionic 5 and Angular 10 shows no active phone call screen.

I also downgradet to
```
"@cometchat-pro/cordova-ionic-chat": "2.1.1",
"@cometchat-pro/ionic-calls": "0.0.6"
```
just like in your sample App since v.0.0.8 still threw the error mentioned [here](https://github.com/cometchat-pro/cordova-ionic-chat-sdk/issues/7#issuecomment-797404980).

Now with v.0.0.6 the js-error is not thrown any more and it seems like the connection is stable, but the CometChat frontend library is not showing anything, instead you're returned to the chat-view (the calling screen is closed) which is expected routing behavior, but the active call screen / modal is missing. No error messages. And also the client is not asked for microphone access permission since no microphone will be turned on.

Is this an issue in combination with Capacitor 3 and iOS 12.0 build target?

**Comment by kamekaioken** [comment]
Any updates on this? Can you please confirm if this is a bug or a build settings issue?

**Comment by mayur-bhandari** [comment]
Hello @kamekaioken,

Please update the Chat & Calling SDK to the latest version. The latest version of CometChat Cordova Ionic SDK(@cometchat-pro/cordova-ionic-chat) is v2.3.1 & the latest version of CometChat Ionic Calls(@cometchat-pro/ionic-calls) is v2.0.2.

Also, you need to update the maven URL in the project level build gradle file from "https://dl.bintray.com/cometchat/pro" to "https://dl.cloudsmith.io/public/cometchat/cometchat-pro-android/maven/".
