### ISSUE TITLE
Closing App during ongoing call is not closing the Call Screen for other participant

### ISSUE THREAD

**Issue by kamekaioken** [cometchat-pro/cordova-ionic-chat-sdk#8]
### Describe the problem

When two users are calling and one of them is killing the App, the onUserLeft callback is called on the other side but the calling screen is not closed. It looks like as if the other participant is still there.

### What was the expected behavior?

I would expect that the call screen is closed on the other side or if there is some sort of method to close the call screen manually.

### Reproduction

- Alice calls Bob
- Bob accepts Alice call
- Alice and Bob are calling
- Bob kills his App
- Alice does not hear Bob anymore but the oingoing call screen is only closed when Alice "hangs up"

### Environment

- "@angular/core": "~10.0.0"
- "@ionic/angular": "^5.5.2"
- "@cometchat-pro/cordova-ionic-chat": "2.3.4"
- "@cometchat-pro/ionic-calls": "2.0.2"

**Comment by kamekaioken** [comment]
Can you please confirm if this is a bug and if this is gonna be fixed?

**Comment by kamekaioken** [comment]
Any updates on this?

**Comment by mayur-bhandari** [comment]
Hello @kamekaioken,

We have fixed this issue in the latest release. Please update the CometChat Cordova Ionic SDK(@cometchat-pro/cordova-ionic-chat) to `v2.4.1` & CometChat Ionic Calls(@cometchat-pro/ionic-calls) to `v2.1.2`. Please let us know if you are still facing this issue.

**Comment by kamekaioken** [comment]
Thanks, the update solved the bug.
