### ISSUE TITLE
Swiping down (closing) the ongoing call screen does not end the call but the screen is gone forever

### ISSUE THREAD

**Issue by kamekaioken** [cometchat-pro/cordova-ionic-chat-sdk#9]
### Describe the problem

When two users are calling and one of them is swiping down the ongoing call screen (the ios card modal), the call is not ended but the screen cannot be reconstructed again. The screen is gone and the participant can only hang up the call by terminating the App.

### What was the expected behavior?

Wether the call should be ended or it should be possible to recreate the screen again through code.

### Reproduction

- Alice calls Bob
- Bob accepts Alice call on an iOS Device
- Alice and Bob are calling
- Bob swipes down the card modal of the ongoing call
- Alice and Bob are still calling but now Bob is not able to hang up the call but by killing the App

### Environment

- "@angular/core": "~10.0.0"
- "@ionic/angular": "^5.5.2"
- "@cometchat-pro/cordova-ionic-chat": "2.3.4"
- "@cometchat-pro/ionic-calls": "2.0.2"

**Comment by kamekaioken** [comment]
Can you please confirm if this is a bug and if this is gonna be fixed?

**Comment by kamekaioken** [comment]
Any updates on this?

**Comment by mayur-bhandari** [comment]
Hello @kamekaioken,

We have fixed this issue in the latest release. Please update the CometChat Cordova Ionic SDK(@cometchat-pro/cordova-ionic-chat) to `v2.4.1` & CometChat Ionic Calls(@cometchat-pro/ionic-calls) to `v2.1.2`. Please let us know if you are still facing this issue.

**Comment by kamekaioken** [comment]
Thanks, the update solved the bug.
